# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'app-danceblue' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for app-danceblue
  pod 'Firebase/Core'
  pod 'Fabric', '~> 1.9.0'
  pod 'Crashlytics', '~> 3.12.0'
  pod 'Firebase/Database'
  pod 'Firebase/DynamicLinks'
  pod 'Firebase/Messaging'
  pod 'Firebase/Storage'
  pod 'XCGLogger'
  pod 'ObjectMapper'
  pod 'Gifu'
  pod 'Kingfisher'
  pod 'DeckTransition', '~> 2.0'
  pod "SAConfettiView"
  pod 'Alamofire'
  pod 'SwiftyJSON'

end
